name: My-GitHubActions

on:
  push:
    branches:
      - main
      
jobs:
  my_testing:
#    runs-on: ubuntu-latest
#    
#    steps:
#      - name: Print Hello Message for testing
#        run: echo "Hello World"
#      - id: step1
#        run: echo ${{jobs.steps.name}}
#    
#    outputs: |
#      echo ${{jobs.steps.id}}
     runs-on: ubuntu-latest
     outputs:
        output1: ${{ steps.step1.outputs.test }}
        output2: ${{ steps.step2.outputs.test }}
     steps:
      - id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "test=world" >> $GITHUB_OUTPUT
