name: My-GitHubActions

on:
  push:
    branches:
      - main
      
jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message for testing
      run: echo "Hello World"
  my_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Message for deploying
      run: echo "Hello World"
