name: example
on:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        name: step1_name
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - name: step2_name
        run: echo ${{steps.step1.test}}
    
