name: My-GitHubActions

on:
  push:
    branches:
      - main
      
jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello Message for testing
        run: echo "Hello World"
      - id: step1
        run: echo ${{steps.name.id}}
    
    outputs: |
      echo ${{ steps.name }}
