name: example2
on:
  push:
    branches:
      - main

jobs:
  if-windows-else:
    runs-on: ubuntu-latest
    steps:
      - name: condition 1
        if: runner.os == "Windows"
        run: echo "Hello $RUNNER_OS."
      - name: condition 2
        if: runner.os != "Windows"
        run: echo "Hello $RUNNER_OS."
