name: Slack Notifications

on:
  push:
    branches: [ master ]

jobs:
  notifySlack:

    runs-on: ubuntu-latest

    steps:
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_WEBHOOK_URL }}
      uses: abinoda/slack-action@master
      with:
        args: '{\"channel\":\"C04DVFKPG3T\",\"text\":\"hello world\"}'
